version: '2'

services:
  app:
    image: yongshin/docker-node-app
    environment:
      PORT: 4000
      MONGODB_SERVICE_SERVICE_HOST: "mongodb1"
    ports:
      - 4000
    labels:
      - "interlock.hostname=test"
      - "interlock.domain=local"
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network

  db:
    restart: always
    image: clusterhq/mongodb
    container_name: "mongodb1"
    networks:
      - backend-network
    ports:
     - "27017:27017"
    volumes:
     - db:/data/db

  interlock:
    image: ehazlett/interlock:latest
    command: -D run
    tty: true
    ports:
      - 4000
    networks:
      - frontend-network
    environment:
      INTERLOCK_CONFIG: |
        ListenAddr = ":8080"
        DockerURL = "${SWARM_HOST}"
        TLSCACert = "/certs/ca.pem"
        TLSCert = "/certs/cert.pem"
        TLSKey = "/certs/key.pem"
        [[Extensions]]
        Name = "nginx"
        ConfigPath = "/etc/nginx/nginx.conf"
        PidPath = "/var/run/nginx.pid"
        TemplatePath = ""
        MaxConn = 1024
        Port = 80
        NginxPlusEnabled = false
    volumes:
      - nginx:/etc/nginx
      - ucp-node-certs:/certs
    restart: always

  nginx:
    image: nginx:latest
    networks:
      - frontend-network
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
      - 80:80
    labels:
      - "interlock.ext.name=nginx"
    volumes:
      - nginx:/etc/nginx
    restart: always

volumes:
  db:
    driver: local
  nginx:
    driver: local
  ucp-node-certs:

networks:
  backend-network:
    driver: overlay
  frontend-network:
    driver: overlay
