version: '2'

services:
  app:
    image: $DTR_IPADDR/engineering/docker-app-swarm-nginx:latest
    environment:
      - "PORT=4000"
      - "MONGODB_SERVICE_SERVICE_HOST=mongodb1"
      - "constraint:nodeType==app"
    ports:
      - 4000
    labels:
      - "interlock.hostname=test"
      - "interlock.domain=local"
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network

  db:
    restart: always
    image: clusterhq/mongodb
    container_name: "mongodb1"
    environment:
      - "constraint:nodeType==app"
    networks:
      - backend-network
    ports:
     - "27017:27017"
    volumes:
     - db:/data/db

  nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
      - 80:80
    labels:
      - "interlock.ext.name=nginx"
    links:
      - app
    restart: always


volumes:
  db:
    driver: local

networks:
  backend-network:
    driver: overlay
  frontend-network:
    external:
      name: frontend-network
