version: '2'

services:
  app:
    image: $DTR_IPADDR/engineering/docker-node-app:latest
    environment:
      - "MONGODB_SERVICE_SERVICE_HOST=mongodb1"
      - "constraint:nodeType==app"
    ports:
      - 4000
    labels:
      - "interlock.hostname=test"
      - "interlock.domain=local"
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network

  db:
    restart: always
    image: clusterhq/mongodb
    container_name: "mongodb1"
    environment:
      - "constraint:nodeType==app"
    networks:
      - backend-network
    ports:
     - "27017:27017"
    volumes:
     - db:/data/db

volumes:
  db:
    driver: local
