version: '2'

services:
  app:
    image: yongshin/docker-node-app
    environment:
      PORT: 4000
      MONGODB_SERVICE_SERVICE_HOST: "mongodb1"
    ports:
      - 4000
    labels:
      - "interlock.hostname=test"
      - "interlock.domain=local"
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network

  db:
    restart: always
    image: clusterhq/mongodb
    container_name: "mongodb1"
    networks:
      - backend-network
    ports:
     - "27017:27017"
    volumes:
     - db:/data/db

  interlock:
    image: ehazlett/interlock
    command: -D run -c /etc/interlock/config.toml
    tty: true
    ports:
      - 4000
    networks:
      - frontend-network
    environment:
      INTERLOCK_CONFIG: |
        ListenAddr = ":8080"
        DockerURL = "${SWARM_HOST}"
        TLSCACert = "/var/lib/boot2docker/ca.pem"
        TLSCert = "/var/lib/boot2docker/server.pem"
        TLSKey = "/var/lib/boot2docker/server-key.pem"

        [[Extensions]]
        Name = "nginx"
        ConfigPath = "/etc/nginx/nginx.conf"
        PidPath = "/var/run/nginx.pid"
        TemplatePath = ""
        MaxConn = 1024
        Port = 80
    volumes:
      - /var/lib/boot2docker:/var/lib/boot2docker:ro

  nginx:
    image: nginx:latest
    networks:
      - frontend-network
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
      - 80:80
    labels:
      - "interlock.ext.name=nginx"

volumes:
  db:
    driver: local

networks:
  backend-network:
    driver: overlay
  frontend-network:
    driver: overlay
